spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true -> sql 을 system out 으로 출력
        format_sql: true

logging:
  level:
    # show_sql 과 달리 sql 을 logging 으로 출력
    org.hibernate.SQL: debug
    org.hibernate.type: trace
